# Generated by Django 2.2.5 on 2019-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='horario_func',
            field=models.TextField(),
        ),
    ]
